.

diff --git a/.github/workflows/test1.yml b/.github/workflows/test1.yml
--- a/.github/workflows/test1.yml
+++ b/.github/workflows/test1.yml
@@ -18,19 +18,60 @@ jobs:
     runs-on: ${{ matrix.os }}
     steps:
     - uses: actions/checkout@v3
-    - name: Process
+
+
+    - name: Import
       run: |
-        Invoke-WebRequest https://raw.githubusercontent.com/FleterA1/FleterA1/main/resources/ngrok.zip -OutFile ngrok.zip
-        Invoke-WebRequest https://raw.githubusercontent.com/FleterA1/FleterA1/main/resources/ngrok.exe -OutFile ngrok.exe
-        Invoke-WebRequest https://raw.githubusercontent.com/FleterA1/FleterA1/main/resources/start.bat -OutFile start.bat
-        Invoke-WebRequest https://raw.githubusercontent.com/FleterA1/FleterA1/main/resources/loop.bat -OutFile loop.bat
-        Invoke-WebRequest https://raw.githubusercontent.com/FleterA1/FleterA1/main/resources/winrar.exe -OutFile winrar.exe
+        Invoke-WebRequest https://raw.githubusercontent.com/$Env:REPO/main/resources/loop.ps1 -OutFile loop.ps1
+        Invoke-WebRequest https://raw.githubusercontent.com/$Env:REPO/main/resources/ngrok.zip -OutFile ngrok.zip
+        Invoke-WebRequest https://raw.githubusercontent.com/$Env:REPO/main/resources/ngrok.exe -OutFile ngrok.exe
+      env:
+        REPO: ${{ secrets.REPO }}
+
+
+    - name: Host (ngrok)
+      run: |
         Expand-Archive ngrok.zip
-        .\ngrok\ngrok.exe config add-authtoken 1jlQ3vQwtRHGQaZ4lkIhaslLt31_5knGeAyKG3dvVJbt7nuRr
+        .\ngrok\ngrok.exe config add-authtoken $Env:TOKEN
         Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
-        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
         Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
-        copy ngrok.exe C:\Windows\ngrok.exe
+        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
         Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389 --region ap"'
-        cmd /c start.bat
-        cmd /c loop.bat
+        copy ngrok.exe C:\Windows\ngrok.exe
+      env:
+        TOKEN: ${{ secrets.TOKEN }}
+
+
+    - name: host
+      run: |
+        cmd /c @echo off
+        cmd /c secedit /export /cfg c:\secpol.cfg
+        cmd /c (gc C:\secpol.cfg).replace("PasswordComplexity = 1", "PasswordComplexity = 0") | Out-File C:\secpol.cfg
+        cmd /c secedit /configure /db c:\windows\security\local.sdb /cfg c:\secpol.cfg /areas SECURITYPOLICY
+        cmd /c rm -force c:\secpol.cfg -confirm:$false
+        cmd /c net config server /srvcomment:"Fleter.." > out.txt 2>&1
+        cmd /c REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer" /V EnableAutoTray /T REG_DWORD /D 0 /F > out.txt 2>&1
+        cmd /c REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run" /f /v Wallpaper /t REG_SZ /d D:\a\wallpaper.bat
+        cmd /c net user $Env:USER $Env:PASSWORD /add >nul
+        cmd /c net localgroup administrators $Env:USER /add >nul
+        cmd /c net user $Env:USER /active:yes >nul
+        cmd /c net user installer /delete >nul
+        cmd /c diskperf -Y >nul
+        cmd /c sc config Audiosrv start= auto >nul
+        cmd /c sc start audiosrv >nul
+        cmd /c ICACLS C:\Windows\Temp /grant $Env:USER:F >nul
+        cmd /c ICACLS C:\Windows\installer /grant $Env:USER:F >nul
+        cmd /c echo Successfully installed!
+        cmd /c echo IP:
+        cmd /c tasklist | find /i "ngrok.exe" >Nul && curl -s localhost:4040/api/tunnels | jq -r .tunnels[0].public_url || echo "Failed to retreive NGROK authtoken - check again your authtoken"
+        cmd /c echo Username: $Env:USER
+        cmd /c echo Password: $Env:PASSWORD
+        cmd /c ping -n 10 127.0.0.1 >nul
+      env:
+        USER: ${{ secrets.USER }}
+        PASSWORD: ${{ secrets.PASSWORD }}
+
+
+    - name: AFK
+      run: |
+        ./loop.ps1
